services:
  db:
    image: postgres:16
    container_name: gestor_peliculas_db

    environment:
      POSTGRES_USER: peliculas_user
      POSTGRES_PASSWORD: peliculas_pass
      POSTGRES_DB: peliculas_db

    ports:
      - "5433:5432"

    volumes:
      - peliculas_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: gestor_peliculas_pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "8081:80"

volumes:
  peliculas_data: